[project]
name = "tg_bot"
version = "0.1.0"
description = "telegram-bot"
requires-python = ">=3.13"
dependencies = [
    "aiomysql>=0.2.0",
    "cryptography>=44.0.2",
    "ormar>=0.20.2",
    "python-telegram-bot>=22.0",
]
